### ISSUE TITLE
[로그인] 아이디 / 비밀번호 실제 문구 입력시 너무 왼쪽 벽에 달라붙습니다.

### ISSUE THREAD

**Issue by nepp-plus** [Lyne121/WITHME#3]
hint에 띄어쓰기를 해서 왼쪽  보다는

padding값을 잘 이용해보는 방안으로 수정해주세요.

**Comment by Lyne121** [comment]
해결했습니다

**Comment by nepp-plus** [comment]
당겨서 테스트해보고 괜찮으면 이슈 닫겠습니다.

**Comment by nepp-plus** [comment]
아예 paddingHorizontal로 양방향 여백으로 해결하셨나보네요.

확인했습니다~!
