### ISSUE TITLE
[첫 로딩화면] 액션바 (화면제목) 없애주세요.

### ISSUE THREAD

**Issue by nepp-plus** [Lyne121/WITHME#4]
로딩화면에서는 보통 noactionbar 계열로 테마를 적용합니다.

manifests에서  해당 화면의 테마를 따로 변경해봐주세요.
  - 트렐로에서 manifest 로 검색해보면 적용하는 방법이 있을겁니다.

**Comment by Lyne121** [comment]
해결했습니다
