### ISSUE TITLE
[비밀번호 찾기] 버튼을 눌러도 아무 응답이 없습니다.

### ISSUE THREAD

**Issue by nepp-plus** [Lyne121/WITHME#5]
비번찾기 화면을 하나 따로 만들어서, 실제로 동작하게 해주세요.

api.gudoc.in/api/docs 문서에 보면,

POST - /user/find/password   기능을 활용하면

서버에서 임시비밀번호를 만들어서 메일로 보내드릴거에요.

파라미터들이 뭐가 필요한지 읽어보시고, 해당 파라미터들을 화면에서 받아서 서버로 전송해주시면 됩니다.

**Comment by Lyne121** [comment]
완료했습니다.

**Comment by nepp-plus** [comment]
닉네임 CKJ / 이메일 cho881020@gmail.com 으로 테스트 해보니 비번 변경 메일이 안옵니다.

혹시 닉네임 / 이메일 반대로 첨부하신거 아닌가요.?

**Comment by Lyne121** [comment]
테스트 해본 결과 수정되었습니다.
