### ISSUE TITLE
[아이디/비번찾기]  상단 버튼 2개 미작동

### ISSUE THREAD

**Issue by nepp-plus** [Lyne121/WITHME#9]
아이디 찾기와 비밀번호 찾기 화면을 따로따로 레이아웃으로 구성해두신것 같은데,

두개의 화면이 실제로 다른 입력값을 받아서 각자의 기능을 수행하게 해주세요.

아이디찾기는 서버 API에서

GET - /user/find/email

항목을 참고하면 됩니다.  닉네임 / 폰번을 맞게 보내주면, 문자로 아이디를 실제로 찾아서 보내드립니다.

버튼별 UI 전환, 실제 아이디찾기 API 이렇게 연동시켜주세요.

**Comment by Lyne121** [comment]
완료했습니다
